// Module Federation Type Declarations
// Generated by package-types.js

declare module 'files_tab/Plugin' {
import type { TabPlugin } from '@tab-contract';
declare const FilesTabPlugin: TabPlugin;
export default FilesTabPlugin;

}


// Module Federation Type Declarations
// Generated by package-types.js

declare module 'hubs_tab/Plugin' {
import type { TabPlugin } from './tab-contract';
declare const HubsTabPlugin: TabPlugin;
export default HubsTabPlugin;

}

